### ISSUE TITLE
[1.12.2] Unable to start server

### ISSUE THREAD

**Issue by Twilix01** [jodlodi/TwilightTweaks#3] opened 2022-01-09 05:05 UTC
Server crashes while starting up with this mod installed. 

Crash report: https://pastebin.com/UUQSMedU

**Comment by jodlodi** [comment] 2022-01-09 11:38
Could you post the "latest.log" that comes from this crash as well?

**Comment by Twilix01** [comment] 2022-01-09 11:45
Sure thing! Here it is.

https://pastebin.com/t2SQFNWP

**Comment by jodlodi** [comment] 2022-04-20 11:40
Apologizes for the several month wait, the issue is fixed now

**Closed as completed by jodlodi** 2022-04-20 11:40 UTC
