### ISSUE TITLE
Issue starting multiplayer server with this mod

### ISSUE THREAD

**Issue by ALJ323** [jodlodi/TwilightTweaks#5] opened 2022-03-09 10:04 UTC
Multiplayer Server crashes when this mod is present.
Tested with just Twilight Forest and this Mod.
[latest.log](https://github.com/jodlodi/TwilightTweaks/files/8213630/latest.log)

**Comment by jodlodi** [comment] 2022-04-20 11:40
the issue is fixed now

**Closed as completed by jodlodi** 2022-04-20 11:40 UTC
