### ISSUE TITLE
Transformation Powder crash, relating to this mod.

### ISSUE THREAD

**Issue by MagmaSlime123** [jodlodi/TwilightTweaks#2] opened 2021-12-24 02:58 UTC
See the crash report. Modlist in it as well.
[crash-2021-12-23_18.46.27-client.txt](https://github.com/jodlodi/TwilightTweaks/files/7772369/crash-2021-12-23_18.46.27-client.txt)

**Comment by jodlodi** [comment] 2021-12-24 13:36
Duplicate of #1 , read my newest response to that

**Closed as completed by jodlodi** 2021-12-24 13:36 UTC
