### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by Biviho** [jodlodi/TwilightTweaks#4] opened 2022-02-15 22:10 UTC
[pastebin](https://pastebin.com/2HRPaCPL)

[latest.log](https://pastebin.com/dD1efPpZ) since you asked it in the other crash issue

**Comment by jodlodi** [comment] 2022-04-20 11:40
Apologizes for the several month wait, the issue is fixed now

**Closed as completed by jodlodi** 2022-04-20 11:40 UTC
