### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by Kasia1403** [jodlodi/TwilightTweaks#1] opened 2021-12-15 19:55 UTC
[crash-2021-12-15_20.42.17-client.txt](https://github.com/jodlodi/TwilightTweaks/files/7722312/crash-2021-12-15_20.42.17-client.txt)
[crash-2021-12-15_20.42.01-client.txt](https://github.com/jodlodi/TwilightTweaks/files/7722313/crash-2021-12-15_20.42.01-client.txt)

**Comment by jodlodi** [comment] 2021-12-16 13:46
Have you tried using the newer version of twilight forest for 1.12? You're using 3.10.1013, but the newest version is 3.11.1021 at https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest/files/3051450

**Comment by Kasia1403** [comment] 2021-12-17 15:28
Sorry, but after updating Twilight Forest to newest version this crash appears:

[crash-2021-12-17_16.21.37-client.txt](https://github.com/jodlodi/TwilightTweaks/files/7736092/crash-2021-12-17_16.21.37-client.txt)

**Comment by jodlodi** [comment] 2021-12-17 16:07
No, I'm pretty sure this is being caused by my mod so there isn't a need to have an issue open on TF's github.
I'm running tests now to see what exactly is causing it

**Comment by jodlodi** [comment] 2021-12-17 16:29
I'm guessing there is some sort of incompatibility going on, since I can't seem to re-create the crash at all. Must be another mod having an issue with mine

**Comment by Kasia1403** [comment] 2021-12-17 16:37
What if I opened issue on TF's Github ? Will they help ?

**Comment by jodlodi** [comment] 2021-12-17 16:39
If they have the free time for it, but maybe they will come to the conclusion that it's my mod's fault and close the issue

**Comment by Kasia1403** [comment] 2021-12-18 08:59
I ran Minecraft onlz with Twilight Forest and this addon mod and everzthing is OK, so this must be other mod's fault.

**Comment by jodlodi** [comment] 2021-12-24 13:35
From my testing, this seems to be an incompatibility with the mod LLibrary. I currently don't know why it's incompatible, but I plan to look into it soon.
If you choose to remove LLibrary, make sure to also delete the folder the mod creates in the "mods" folder called "memory_repo". From my testing, not deleting this also makes the same crash happen.

**Comment by MagmaBro123** [comment] 2021-12-24 16:40
LLibrary is required by, probably many other mods, including Mowzies Mobs.

**Comment by jodlodi** [comment] 2021-12-24 17:06
I know it's a useful mod, this was just my answer to how to fix the problem for now. I don't know why the mods are incompatible and will look into a possible fix

**Comment by Twilix01** [comment] 2022-01-08 04:24
I'd like to add that there may also be compatibility issues with Immersive Engineering as well, as that mod also generates the "memory_repo" folder. It appears to be the same crash as shown in this issue. Hope the fix comes smoothly!

**Comment by jodlodi** [comment] 2022-01-08 14:05
I have solved the issue and the new mod version has been uploaded to CurseForge and is awaiting approval (which can take some time due to CurseForge moderators potentially not working on weekends). 
Thank you all for being patient and for submitting the issues.

**Closed by jodlodi** 2022-01-08 14:05 UTC

**Comment by jodlodi** [comment] 2022-01-08 14:40
The file was approved very quickly!
Link: https://www.curseforge.com/minecraft/mc-mods/twilight-tweaks/files/3598402
